server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_vediosys
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    type: com.alibaba.druid.pool.DruidDataSource

  data:
    mongodb:
      uri: mongodb://localhost:27017/danmu

  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 1500MB

shiro:
  loginUrl: "Login.html"




